stages:
  - deploy

variables:
  GIT_STRATEGY: clone

Deploy Cloudflare:
  stage: deploy
  image: node:24.3.0-slim
  script:
    - npm install
    - npm list
    - npm run deploy
  tags:
    - docker
  rules:
    - if: $CI_COMMIT_BRANCH == "mcp_tool"
    # - if: $CI_COMMIT_BRANCH == "main"