stages:
  - test
  - deploy

variables:
  GIT_STRATEGY: clone

Compile Check:
  stage: test
  image: node:24.3.0-slim
  script:
    - npm install typescript
    - npm list
    - npm run type-check
  tags:
    - docker
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

Deploy Cloudflare:
  stage: deploy
  image: node:24.3.0-slim
  script:
    - npm install wrangler
    - npm list
    - npm run deploy
  tags:
    - docker
  rules:
    - if: $CI_COMMIT_BRANCH == "mcp_tool"