services:
  onboarding_mcp:
    container_name: onboarding_mcp
    build: .
    env_file: .env
    ports:
      - "8787:8787" # mcp server
      - "6274:6274" # mcp inspector (client)
      - "6277:6277" # mcp inspector (server)
    volumes:
      - .:/usr/src/app
    networks:
      aws_molpay:
      aliyun_molpay:

networks:
  aws_molpay:
    external: true
  aliyun_molpay:
    external: true