services:
  cloudflare_mcp:
    container_name: cloudflare_mcp
    build: .
    env_file: .env
    ports:
      - "8787:8787" 
    volumes:
      - .:/usr/src/app
    networks:
      global-net:

networks:
  global-net:
    external: true